// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tender.proto

package web.pb;

public interface TenderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TenderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string companyName = 1;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 1;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();
}
