// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tender.proto

package web.pb;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
