server:
  port: 0

spring:
  application:
    name: tender-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true