server:
  port: 0

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true


grpc:
  client:
    tender-service:
      address: static://localhost:7863
      negotiation-type: plaintext