server:
  port: 8087

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true